"""
Adapter for running the research-radar workflow
and exposing a clean function that returns only a summary.

Used by the MCP server so Claude Desktop can request
a summary for a given paper ID.
"""

from typing import Any, Dict
import uuid
import logging
from research_radar.workflow.graph import build_graph
from research_radar.workflow.state import WorkflowStatus


logger = logging.getLogger(__name__)


def create_initial_state(paper_id: str) -> dict:
    """Create initial workflow state.

    Args:
        paper_id: ID of paper.

    Returns:
        Initial workflow state dictionary.
    """
    return {
        "workflow_id": str(uuid.uuid4()),
        "paper_id": paper_id,
        "metadata": None,
        "content": None,
        "status": WorkflowStatus.PENDING.value,
        "error": None,
        "required_keywords": [
            "large language models (LLMs)",
            "instruction following (IF)",
            "multi-turn instructions",
            "system-prompted instructions",
            "human-annotated benchmarks",
            "rubrics",
            "LLMs",
            "commonsense reasoning",
            "Global PIQA",
            "language varieties",
            "culturally-specific elements",
        ],
    }


def run_workflow_for_paper(paper_id: str) -> Dict[str, Any]:
    """
    Run the full workflow and extract the final paper summary
    from the workflow output state.

    Args:
        paper_id: Hugging Face paper ID string

    Returns:
        dict with:
            - paper_id: the ID analyzed
            - summary: the summary generated by the workflow
    """
    logger.info("Initializing workflow for paper_id=%s", paper_id)

    graph = build_graph()
    initial_state = create_initial_state(paper_id=paper_id)

    result = graph.invoke(initial_state)

    summary = result.get("summary")

    if summary is None:
        logger.warning(
            "Workflow completed but 'summary' was missing from state. "
            "Returning minimal output."
        )
        summary = (
            "No summary was generated. This may happen if the paper was not "
            "considered relevant or the analysis step is not implemented yet."
        )

    return {
        "paper_id": result.get("paper_id", paper_id),
        "summary": summary,
    }
