"""Constants defining workflow node type identifiers."""

EXTRACT_PAPER_INFORMATION = "extract_paper_information"
EXTRACT_YOUTUBE_INFORMATION = "extract_youtube_information"
FILTER_PAPER_RELEVANCE = "filter_paper_relevance"
EXTRACT_PAPER_CONTENT = "extract_paper_content"
EXTRACT_YOUTUBE_CONTENT = "extract_youtube_content"
EMBED_CONTENT = "embed_content"
ANALYZE_PAPER = "analyze_paper"
PUBLISH_RESULTS = "publish_results"
