EXTRACT_PAPER_INFORMATION = "extract_paper_information"
FILTER_PAPER_RELEVANCE = "filter_paper_relevance"
EXTRACT_PAPER_CONTENT = "extract_paper_content"
EMBED_PAPER = "embed_paper"
ANALYZE_PAPER = "analyze_paper"
PUBLISH_RESULTS = "publish_results"
